-- Seed inicial del catálogo real (public.figures)
-- Alineado con mockFigures.js + album_collections (016).
-- Ejecutar en Supabase Dashboard → SQL Editor (Run).
-- Idempotente: ON CONFLICT (id) DO UPDATE — seguro re-ejecutar.

-- ---------------------------------------------------------------------------
-- 5 figuritas principales (IDs estables '1'–'5', mismos que 001_initial_schema)
-- collection_id → 8 colecciones remotas (plazas, cultura, arquitectura, …)
-- Sin image_url (mock tampoco las define; fotos las aportan los jugadores).
-- ---------------------------------------------------------------------------

insert into public.figures (
  id,
  title,
  description,
  rarity,
  lat,
  lng,
  image_url,
  active,
  capture_radius,
  is_bonus,
  is_hidden,
  unlock_order,
  reveal_after_count,
  bonus_type,
  reveal_radius,
  marker_icon_url,
  marker_icon_size,
  collection_id,
  category,
  page
) values
  (
    '1',
    'Catedral de San Fernando',
    'Patrimonio histórico del centro de la ciudad.',
    'común',
    -34.4439,
    -58.5597,
    null,
    true,
    250,
    false,
    false,
    1,
    0,
    null,
    200,
    null,
    48,
    'arquitectura',
    null,
    2
  ),
  (
    '2',
    'Plaza San Martín',
    'Corazón cívico y punto de encuentro local.',
    'común',
    -34.4428,
    -58.5589,
    null,
    true,
    250,
    false,
    false,
    2,
    0,
    null,
    200,
    null,
    48,
    'plazas',
    null,
    1
  ),
  (
    '3',
    'Costanera del Delta',
    'Vistas al río y paseos al aire libre.',
    'rara',
    -34.4365,
    -58.5542,
    null,
    true,
    250,
    false,
    false,
    3,
    0,
    null,
    200,
    null,
    48,
    'plazas',
    null,
    1
  ),
  (
    '4',
    'Museo Histórico',
    'Historia y cultura de San Fernando.',
    'épica',
    -34.4451,
    -58.5563,
    null,
    true,
    250,
    false,
    false,
    4,
    0,
    null,
    200,
    null,
    48,
    'cultura',
    null,
    2
  ),
  (
    '5',
    'Estación Fluvial',
    'Puerta de entrada al delta.',
    'legendaria',
    -34.4402,
    -58.5621,
    null,
    true,
    250,
    false,
    false,
    5,
    0,
    null,
    200,
    null,
    48,
    'arquitectura',
    null,
    2
  )
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  rarity = excluded.rarity,
  lat = excluded.lat,
  lng = excluded.lng,
  image_url = excluded.image_url,
  active = excluded.active,
  capture_radius = excluded.capture_radius,
  is_bonus = excluded.is_bonus,
  is_hidden = excluded.is_hidden,
  unlock_order = excluded.unlock_order,
  reveal_after_count = excluded.reveal_after_count,
  bonus_type = excluded.bonus_type,
  reveal_radius = excluded.reveal_radius,
  marker_icon_url = excluded.marker_icon_url,
  marker_icon_size = excluded.marker_icon_size,
  collection_id = excluded.collection_id,
  category = excluded.category,
  page = excluded.page;

-- Verificación rápida (opcional, comentar si no querés ver el resultado)
-- select id, title, rarity, collection_id, active, unlock_order from public.figures order by unlock_order;
